### ISSUE TITLE
why does has only one socket connection between server and client?

### ISSUE THREAD

**Issue by cposture** [Wenchy/tinyFTP#1]
In the FTP RFC959, it said that there should be two socket connection between server and client; one is to send command and the other is to send data

**Comment by Wenchy** [comment]
Yes, you are right. But for simplicity, we just use one connection for both control commands and data transfers. That's why it is named tinyFTP.

**Comment by wenchy** [comment]
Yes, you are right. But for simplicity, we just use one connection for both control commands and data transfers. That's why it is named tinyFTP.
